# ---------------------
# Pawbs Engine fly.toml
# ---------------------

# App Configuration

# Name
app = 'pawbs-engine'

# Machine region
primary_region = 'yyz'


# Build Configuration
[build]
	
	# Use included Dockerfile
	dockerfile = "Dockerfile"
	
	
# Dedicated Server Configuration
[[services]]
	
	# Internal WebSocket port
	internal_port = 3000
	protocol = "tcp"
	
	# Public http:// WebSocket port (http:// traffic is automatically redirected to https:// by fly.io)
	[[services.ports]]
		handlers = ["http"]
		port = 3000  
		
	# Public https:// WebSocket port
	[[services.ports]]
		handlers = ["tls"]
		port = 3443
		
		
# HTTP Server Configuration
[[services]]
	
	# Internal Express server port
	internal_port = 4000
	protocol = "tcp"
	
	# Public http:// Express server port (http:// traffic is automatically redirected to https:// by fly.io)
	[[services.ports]]
		handlers = ["http"]
		port = 80
		
	# Public https:// Express server port
	[[services.ports]]
		handlers = ["tls"]
		port = 443
		
		
# Signaling Server Configuration
[[services]]
	
	# Internal WebSocket port
	internal_port = 5000
	protocol = "tcp"
	
	# Public http:// WebSocket port (http:// traffic is automatically redirected to https:// by fly.io)
	[[services.ports]]
		handlers = ["http"]
		port = 5000  
		
	# Public https:// WebSocket port
	[[services.ports]]
		handlers = ["tls"]
		port = 5443
		
		
# Fly.io Machine Configuration
[[vm]]
	memory = '1gb'
	cpu_kind = 'shared'
	cpus = 1
	memory_mb = 512
	
[[restart]]
	policy = "never"